### PR TITLE
fix(tasks): list tasks with better formatting

### LINKED ISSUE #3750: sctool tasks table is broken after upgrading to 3.2.6
How `sctool tasks` looked like in 3.2.5:
```
Cluster: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
╭─────────────────────────────────────────────┬──────────────┬────────────────────┬──────────┬─────────┬───────┬────────────────────────┬────────────────────────┬─────────┬────────────────────────╮
│ Task                                        │ Schedule     │ Window             │ Timezone │ Success │ Error │ Last Success           │ Last Error             │ Status  │ Next                   │
├─────────────────────────────────────────────┼──────────────┼────────────────────┼──────────┼─────────┼───────┼────────────────────────┼────────────────────────┼─────────┼────────────────────────┤
│ backup/65f3d36a-88ef-42af-b7be-a9515298f7e5 │ 0 */3 * * *  │                    │ Etc/UTC  │ 2218    │ 4     │ 12 Mar 24 15:06:56 UTC │ 09 Feb 24 21:00:21 UTC │ RUNNING │                        │
│ healthcheck/rest                            │ @every 1m0s  │                    │ Etc/UTC  │ 472867  │ 2     │ 12 Mar 24 18:03:54 UTC │ 02 Nov 23 18:09:31 UTC │ DONE    │ 12 Mar 24 18:04:54 UTC │
│ healthcheck/cql                             │ @every 15s   │                    │ Etc/UTC  │ 1887073 │ 0     │ 12 Mar 24 18:04:40 UTC │                        │ DONE    │ 12 Mar 24 18:04:55 UTC │
│ healthcheck/alternator                      │ @every 15s   │                    │ Etc/UTC  │ 1887123 │ 0     │ 12 Mar 24 18:04:40 UTC │                        │ DONE    │ 12 Mar 24 18:04:55 UTC │
│ repair/06a55001-9ca2-454f-aeb9-464b1cd2d3f2 │              │                    │ Etc/UTC  │ 1       │ 0     │ 13 Dec 23 23:47:09 UTC │                        │ DONE    │                        │
│ repair/21c654d7-9cf1-4937-99f6-a57cc104be6c │              │                    │ Etc/UTC  │ 1       │ 0     │ 11 Jul 23 17:58:24 UTC │                        │ DONE    │                        │
│ repair/62e817ba-8c55-4734-91b1-5a2f67ee2e65 │              │                    │ Etc/UTC  │ 1       │ 0     │ 10 Jul 23 22:59:09 UTC │                        │ DONE    │                        │
│ repair/all-weekly                           │ 0 23 * * SAT │ Sun-21:30,Mon-3:30 │ Etc/UTC  │ 32      │ 8     │ 26 Feb 24 02:38:35 UTC │ 10 Dec 23 22:45:29 UTC │ WAITING │ 17 Mar 24 21:30:00 UTC │
╰─────────────────────────────────────────────┴──────────────┴────────────────────┴──────────┴─────────┴───────┴────────────────────────┴────────────────────────┴─────────┴────────────────────────╯
```

After upgrading from 3.2.5 to 3.2.6, this is how sctool tasks is shown:
```
╭─────────────────────────────────────────────┬─────────────────────────────────────────────────────────────┬────────────────────┬──────────┬─────────┬───────┬────────────────────────┬────────────────────────┬─────────┬────────────────────────╮
│ Task                                        │ Schedule                                                    │ Window             │ Timezone │ Success │ Error │ Last Success           │ Last Error             │ Status  │ Next                   │
├─────────────────────────────────────────────┼─────────────────────────────────────────────────────────────┼────────────────────┼──────────┼─────────┼───────┼────────────────────────┼────────────────────────┼─────────┼────────────────────────┤
│ backup/65f3d36a-88ef-42af-b7be-a9515298f7e5 │ {"spec":"0 */3 * * *","start_date":"0001-01-01T00:00:00Z"}  │                    │ Etc/UTC  │ 2219    │ 4     │ 12 Mar 24 18:07:41 UTC │ 09 Feb 24 21:00:21 UTC │ DONE    │ 13 Mar 24 00:00:00 UTC │
│ healthcheck/rest                            │ {"spec":"@every 1m0s","start_date":"0001-01-01T00:00:00Z"}  │                    │ Etc/UTC  │ 473002  │ 2     │ 12 Mar 24 20:19:16 UTC │ 02 Nov 23 18:09:31 UTC │ DONE    │ 12 Mar 24 21:24:52 UTC │
│ healthcheck/cql                             │ {"spec":"@every 15s","start_date":"0001-01-01T00:00:00Z"}   │                    │ Etc/UTC  │ 1887586 │ 0     │ 12 Mar 24 20:19:40 UTC │                        │ DONE    │ 12 Mar 24 21:24:07 UTC │
│ healthcheck/alternator                      │ {"spec":"@every 15s","start_date":"0001-01-01T00:00:00Z"}   │                    │ Etc/UTC  │ 1887636 │ 0     │ 12 Mar 24 20:19:36 UTC │                        │ DONE    │ 12 Mar 24 21:24:07 UTC │
│ repair/06a55001-9ca2-454f-aeb9-464b1cd2d3f2 │ {"spec":"","start_date":"0001-01-01T00:00:00Z"}             │                    │ Etc/UTC  │ 1       │ 0     │ 13 Dec 23 23:47:09 UTC │                        │ DONE    │                        │
│ repair/21c654d7-9cf1-4937-99f6-a57cc104be6c │ {"spec":"","start_date":"0001-01-01T00:00:00Z"}             │                    │ Etc/UTC  │ 1       │ 0     │ 11 Jul 23 17:58:24 UTC │                        │ DONE    │                        │
│ repair/62e817ba-8c55-4734-91b1-5a2f67ee2e65 │ {"spec":"","start_date":"0001-01-01T00:00:00Z"}             │                    │ Etc/UTC  │ 1       │ 0     │ 10 Jul 23 22:59:09 UTC │                        │ DONE    │                        │
│ repair/all-weekly                           │ {"spec":"0 23 * * SAT","start_date":"0001-01-01T00:00:00Z"} │ Sun-21:30,Mon-3:30 │ Etc/UTC  │ 32      │ 8     │ 26 Feb 24 02:38:35 UTC │ 10 Dec 23 22:45:29 UTC │ WAITING │ 17 Mar 24 21:30:00 UTC │
╰─────────────────────────────────────────────┴─────────────────────────────────────────────────────────────┴────────────────────┴──────────┴─────────┴───────┴────────────────────────┴────────────────────────┴─────────┴────────────────────────╯
```

### PR DESCRIPTION
**Pull request by karol-kokoszka**
Fixed #3750 

Current output:
```
│ repair/2e3c9d7c-28aa-45ab-9c33-be14c1bdc5a1 │ 0 23 * * SAT; starts: 2024-08-24 23:00:00 UTC │        │ Europe/Warsaw │ 0       │ 0     │                        │                        │ NEW    │ 25 Aug 24 01:00:00 CEST │
│ repair/5954b6b0-0b17-498e-9db4-39ee25c59f9a │ 0 23 * * SAT                                  │        │ Europe/Warsaw │ 0       │ 0     │                        │                        │ NEW    │ 30 Mar 24 23:00:00 CET  │

```

---

Please make sure that:
- Code is split to commits that address a single change
- Commit messages are informative
- Commit titles have module prefix
- Commit titles have issue nr. suffix

### CODE REVIEW

File: pkg/managerclient/model.go [hunk 1]
```diff
@@ -513,7 +516,18 @@ func (li TaskListItems) Render(w io.Writer) error {
...
+			var cronSpec scheduler.CronSpecification
+			err := json.Unmarshal([]byte(t.Schedule.Cron), &cronSpec)
+			if err != nil {
+				schedule = t.Schedule.Cron
+			} else {
+				schedule = cronSpec.Spec
+				if cronSpec.StartDate.After(timeutc.Now()) {
+					c := scheduler.MustCron(cronSpec.Spec, cronSpec.StartDate)
+					schedule += fmt.Sprintf("; starts: %s UTC",
+						c.Next(cronSpec.StartDate).Format("2006-01-02 15:04:05"))
```
Comment (Michal-Leszczynski) [inline pkg/managerclient/model.go:528]: "starts" sound a little like the task is going to be executed right on start date, but it will be executed according to crone, but not earlier than the start date. Could we change it to something like "with first activation after %s"?

The composition of start date and cron can be a little bit confusing, so could we extend sctool docs with a sentence about how they interact with each other?

File: pkg/restapi/task.go [hunk 2]
```diff
@@ -151,6 +151,9 @@ func (h *taskHandler) parseTask(r *http.Request) (*scheduler.Task, error) {
 	if err := render.DecodeJSON(r.Body, &t); err != nil {
 		return nil, err
 	}
+	if !t.Sched.StartDate.IsZero() && t.Sched.Cron.Spec != "" {
+		t.Sched.Cron.StartDate = t.Sched.StartDate
+	}
```
Comment (Michal-Leszczynski) [inline pkg/restapi/task.go:156]: Can there be a situation where `t.Sched.Cron.StartDate` is not zero value but gets overwritten? And why is it done here?

**Review by Michal-Leszczynski — COMMENTED** [review]
@karol-kokoszka ~do you have some sample sctool output to validate proposed changes?~ now I see it!

File: pkg/managerclient/model.go (hunk 1 above)
Comment (karol-kokoszka) [reply pkg/managerclient/model.go:528]: It makes sense, let me change the output to suggested "with first activation after".

File: pkg/restapi/task.go (hunk 2 above)
Comment (karol-kokoszka) [reply pkg/restapi/task.go:156]: Not really, seems it's a fix for a hidden bug, where adding the task didn't set correct StartDate in Cron :see_no_evil: This value will not be overriden, This value just must be copied from Sched.StartDate.

**Comment by karol-kokoszka** [comment]
@Michal-Leszczynski I want to include that into 3.2.7
