### PR TITLE
Backup: use old driver side describe for older Scylla versions

### LINKED ISSUE #3903: Manager 3.3.0-dev fails to re-execute the backup task done by Manager 3.2.8, Scylla 2022.1
**Preconditions:**
- Manager 3.2.8
- There is a successful backup task (DONE) run on 3.2.8

**Steps:**
1. Upgrade the Manager to 3.3.0-dev;
2. Re-execute the backup task from preconditions:
`PUT /api/v1/cluster/3b4b3574-d1a4-4fcd-8082-789108a816b8/task/backup/3603fd9f-8bb7-4056-83ef-fb1c7beabb10/start?continue=false`

**Actual result:**
The task fails (ERROR) with error `"status":"ERROR","cause":"await schema: dump schema: describe schema with internals: line 1:0 no viable alternative at input 'DESCRIBE'"`
```
Jun 25 09:28:17 manager-upgrade-manager--monitor-node-338ecc62-1 scylla-manager[22613]: {"L":"ERROR","T":"2024-06-25T09:28:17.493Z","N":"backup.await_schema","M":"Awaiting schema agreement failed see exact errors above","duration":"42.660534ms","_trace_id":"H0bYorOfTBi0vPgmYujEJA","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\ngithub.com/scylladb/scylla-manager/v3/pkg/service/backup.(*Service).Backup.func11.1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/backup/service.go:899\ngithub.com/scylladb/scylla-manager/v3/pkg/service/backup.(*Service).Backup.func11\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/backup/service.go:907\ngithub.com/scylladb/scylla-manager/v3/pkg/service/backup.(*Service).Backup\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/backup/service.go:911\ngithub.com/scylladb/scylla-manager/v3/pkg/service/backup.Runner.Run\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/backup/runner.go:26\ngithub.com/scylladb/scylla-manager/v3/pkg/service/scheduler.PolicyRunner.Run\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/scheduler/policy.go:32\ngithub.com/scylladb/scylla-manager/v3/pkg/service/scheduler.(*Service).run\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/scheduler/service.go:451\ngithub.com/scylladb/scylla-manager/v3/pkg/scheduler.(*Scheduler[...]).asyncRun.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/scheduler/scheduler.go:404"}
Jun 25 09:28:17 manager-upgrade-manager--monitor-node-338ecc62-1 scylla-manager[22613]: {"L":"INFO","T":"2024-06-25T09:28:17.502Z","N":"scheduler.3b4b3574","M":"Run ended with ERROR","task":"backup/3603fd9f-8bb7-4056-83ef-fb1c7beabb10","status":"ERROR","cause":"await schema: dump schema: describe schema with internals: line 1:0 no viable alternative at input 'DESCRIBE'","duration":"578.52041ms","_trace_id":"H0bYorOfTBi0vPgmYujEJA"}
Jun 25 09:28:17 manager-upgrade-manager--monitor-node-338ecc62-1 scylla-manager[22613]: {"L":"ERROR","T":"2024-06-25T09:28:17.502Z","N":"scheduler.3b4b3574","M":"OnRunError","key":"3603fd9f-8bb7-4056-83ef-fb1c7beabb10","retry":0,"error":"await schema: dump schema: describe schema with internals: line 1:0 no viable alternative at input 'DESCRIBE'","errorStack":"github.com/scylladb/scylla-manager/v3/pkg/service/backup.(*Service).Backup.func11\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/backup/service.go:907\ngithub.com/scylladb/scylla-manager/v3/pkg/service/backup.(*Service).Backup\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/backup/service.go:911\ngithub.com/scylladb/scylla-manager/v3/pkg/service/backup.Runner.Run\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/backup/runner.go:26\ngithub.com/scylladb/scylla-manager/v3/pkg/service/scheduler.PolicyRunner.Run\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/scheduler/policy.go:32\ngithub.com/scylladb/scylla-manager/v3/pkg/service/scheduler.(*Service).run\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/scheduler/service.go:451\ngithub.com/scylladb/scylla-manager/v3/pkg/scheduler.(*Scheduler[...]).asyncRun.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/scheduler/scheduler.go:404\nruntime.goexit\n\truntime/asm_amd64.s:1695\n","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\ngithub.com/scylladb/scylla-manager/v3/pkg/scheduler.errorLogListener[...].OnRunError\n\tgithub.com/scylladb/scylla-manager/v3/pkg/scheduler/listener.go:86\ngithub.com/scylladb/scylla-manager/v3/pkg/scheduler.(*Scheduler[...]).onRunEnd\n\tgithub.com/scylladb/scylla-manager/v3/pkg/scheduler/scheduler.go:420\ngithub.com/scylladb/scylla-manager/v3/pkg/scheduler.(*Scheduler[...]).asyncRun.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/scheduler/scheduler.go:405"}
Jun 25 09:28:17 manager-upgrade-manager--monitor-node-338ecc62-1 scylla-manager[22613]: {"L":"INFO","T":"2024-06-25T09:28:17.502Z","N":"scheduler.3b4b3574","M":"Retry backoff","task":"backup/3603fd9f-8bb7-4056-83ef-fb1c7beabb10","backoff":"10m0s","retry":1}
```

**Expected result:**
The task final status is DONE.

**Environment:**
- Scylla 2022.1

**Additional info:**
- Jenkins job: https://jenkins.scylladb.com/job/manager-3.3/job/older-enterprise-ami-upgrade-test/1/

### PR DESCRIPTION
**Pull request by Michal-Leszczynski**
Fixes #3903

### CODE REVIEW

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka This PR is ready for review!

**Comment by karol-kokoszka** [comment]
Thanks ! Just started backup tests against 2022.2 locally to validate the output.

File: pkg/service/backup/worker_schema.go [hunk 1]
```diff
@@ -25,37 +30,47 @@ func (w *worker) DumpSchema(ctx context.Context, clusterSession gocqlx.Session,
...
-	if safe {
-		w.SchemaFilePath = backupspec.RemoteSchemaFile(w.ClusterID, w.TaskID, w.SnapshotTag)
-	} else {
-		w.SchemaFilePath = backupspec.RemoteUnsafeSchemaFile(w.ClusterID, w.TaskID, w.SnapshotTag)
-		w.Logger.Info(ctx, "Backing-up and restoring schema from output of "+
-			"DESCRIBE SCHEMA WITH INTERNALS is supported starting from ScyllaDB 6.0 or 2024.2. "+
-			"Previous versions restore schema via snapshot of system_schema sstables")
+func (w *worker) unsafeDumpSchema(ctx context.Context, session gocqlx.Session) {
+	w.Logger.Info(ctx, "Schema backup for used ScyllaDB version is done via snapshot of system_schema sstables. "+
+		"ScyllaDB Manager will try to create unsafe schema CQL archive, but it won't be used during schema restoration")
```
Comment (karol-kokoszka) [inline pkg/service/backup/worker_schema.go:62]:
```suggestion
	w.Logger.Info(ctx, "Schema backup for used ScyllaDB version is done via snapshot of system_schema sstables. "+
		"ScyllaDB Manager will try to create unsafe schema CQL archive, but it won't be used during schema restoration")
```
