### PR TITLE
Scyllaclient: use different keyspaces in TestClientDescribeRingIntegration

### LINKED ISSUE #3859: TestClientDescribeRingIntegration is flaky
Example logs from failed run:
```
2024-05-16T09:51:35.2181052Z === RUN   TestClientDescribeRingIntegration
2024-05-16T09:51:35.2210409Z 09:51:35.220	[35mDEBUG[0m	HTTP	{"host": "192.168.200.11:10001", "method": "GET", "uri": "/agent/node_info", "duration": "2ms", "status": 200, "bytes": 538}
2024-05-16T09:51:35.2250509Z 09:51:35.224	[35mDEBUG[0m	HTTP	{"host": "192.168.200.12:10001", "method": "GET", "uri": "/agent/node_info", "duration": "3ms", "status": 200, "bytes": 538}
2024-05-16T09:51:35.2282279Z 09:51:35.227	[35mDEBUG[0m	HTTP	{"host": "192.168.200.13:10001", "method": "GET", "uri": "/agent/node_info", "duration": "3ms", "status": 200, "bytes": 538}
2024-05-16T09:51:35.2315308Z 09:51:35.231	[35mDEBUG[0m	HTTP	{"host": "192.168.200.21:10001", "method": "GET", "uri": "/agent/node_info", "duration": "3ms", "status": 200, "bytes": 538}
2024-05-16T09:51:35.2350255Z 09:51:35.234	[35mDEBUG[0m	HTTP	{"host": "192.168.200.22:10001", "method": "GET", "uri": "/agent/node_info", "duration": "3ms", "status": 200, "bytes": 538}
2024-05-16T09:51:35.2386256Z 09:51:35.238	[35mDEBUG[0m	HTTP	{"host": "192.168.200.23:10001", "method": "GET", "uri": "/agent/node_info", "duration": "3ms", "status": 200, "bytes": 538}
2024-05-16T09:51:35.2580013Z 09:51:35.257	[35mDEBUG[0m	HTTP	{"host": "192.168.200.11:10001", "method": "GET", "uri": "/storage_service/keyspaces?replication=tablets", "duration": "2ms", "status": 200, "bytes": 2}
2024-05-16T09:51:35.2586495Z 09:51:35.258	[35mDEBUG[0m	HTTP	{"host": "192.168.200.11:10001", "method": "GET", "uri": "/storage_service/keyspaces?replication=vnodes", "duration": "0ms", "status": 200, "bytes": 126}
2024-05-16T09:51:39.2982673Z 09:51:39.297	[35mDEBUG[0m	HTTP	{"host": "192.168.200.11:10001", "method": "GET", "uri": "/storage_service/keyspaces?replication=tablets", "duration": "0ms", "status": 200, "bytes": 2}
2024-05-16T09:51:39.2986397Z 09:51:39.298	[35mDEBUG[0m	HTTP	{"host": "192.168.200.11:10001", "method": "GET", "uri": "/storage_service/keyspaces?replication=vnodes", "duration": "0ms", "status": 200, "bytes": 136}
2024-05-16T09:51:39.3027204Z 09:51:39.302	[35mDEBUG[0m	HTTP	{"host": "192.168.200.11:10001", "method": "GET", "uri": "/storage_service/describe_ring/test_ks", "duration": "4ms", "status": 200, "bytes": -1}
2024-05-16T09:51:44.5917942Z 09:51:44.591	[35mDEBUG[0m	HTTP	{"host": "192.168.200.11:10001", "method": "GET", "uri": "/storage_service/keyspaces?replication=tablets", "duration": "1ms", "status": 200, "bytes": 11}
2024-05-16T09:51:44.5921698Z 09:51:44.591	[35mDEBUG[0m	HTTP	{"host": "192.168.200.11:10001", "method": "GET", "uri": "/storage_service/keyspaces?replication=vnodes", "duration": "0ms", "status": 200, "bytes": 126}
2024-05-16T09:51:44.5927376Z 09:51:44.592	[35mDEBUG[0m	HTTP	{"host": "192.168.200.11:10001", "method": "GET", "uri": "/storage_service/describe_ring/test_ks?table=test_tab", "duration": "0ms", "status": 200, "bytes": -1}
2024-05-16T09:51:47.4985513Z     client_scylla_integration_test.go:130: Cannot add already existing table "test_tab" to keyspace "test_ks"
2024-05-16T09:51:47.4990100Z --- FAIL: TestClientDescribeRingIntegration (12.28s)
```

### PR DESCRIPTION
**Pull request by Michal-Leszczynski**
Fixes #3859

### CODE REVIEW

File: pkg/scyllaclient/client_scylla_integration_test.go [hunk 1]
```diff
@@ -75,17 +76,20 @@ func TestClientStatusIntegration(t *testing.T) {
...
 func TestClientDescribeRingIntegration(t *testing.T) {
 	testCases := []struct {
+		name            string
 		replicationStmt string
 		replication     scyllaclient.ReplicationStrategy
 		rf              int
 		dcRF            map[string]int
 	}{
 		{
+			name:            "simple_4",
```
Comment (karol-kokoszka) [inline pkg/scyllaclient/client_scylla_integration_test.go:86]: WDYT about randomizing the names by adding UUID for example ?

**Review by karol-kokoszka — APPROVED** [review]

File: pkg/scyllaclient/client_scylla_integration_test.go (hunk 1 above)
Comment (Michal-Leszczynski) [reply pkg/scyllaclient/client_scylla_integration_test.go:86]: I don't see a particular reason in the context of this test, as we won't have 2 tests with the same name here, but this could be an improvement used in all tests. We could introduce a function like:
```go
func getRandomizedName(name string) string {
    return name + "_" + fmt.Sprint(uuid.MustRandom)
}
```
That would be called anytime we want to obtain unique keyspace/table name.
But I would view it as a thing for a separate PR.
