### PR TITLE
Fix alternator tables with dots

### LINKED ISSUE #3165: S3 Backups don't include Alternator keyspace
I have backups configured in the operator.  I assumed the whole cluster would be backed up, but when I examine the structure on S3, it looks like just the system tables, and not my Alternator tables are bing backed up.

```yaml
    backups:
    - name: "daily full cluster backup"
      #rateLimit: ["50"]
      location: ["s3:backups.*******.com"]
      interval: "1d"
    - name: "weekly full cluster backup"
      #rateLimit: ["50"]
      location: ["s3:backups.*******.com"]
      interval: "7d"
```

It looks like it is picking up all of my keyspaces except for alternator ( keyspace.table is: `alternator_bidder-prod-matchtable.bidder-prod-matchtable` -- over 1 TB of data )

Maybe it doesn’t like the `-` in the name?

Here's the output of the task from `sctool`:

```
+-----------------------------------+-----------------------------+----------+----------+----------+--------------+--------+------------------------+------------------------+
| Keyspace                          | Table                       | Progress | Size     | Success  | Deduplicated | Failed | Started at             | Completed at           |
+-----------------------------------+-----------------------------+----------+----------+----------+--------------+--------+------------------------+------------------------+
| system_auth                       | role_members                |     100% |       0B |       0B |           0B |     0B | 23 May 22 12:25:34 UTC | 23 May 22 12:25:34 UTC |
| system_auth                       | roles                       |     100% |     5KiB |     5KiB |         5KiB |     0B | 23 May 22 12:25:34 UTC | 23 May 22 12:25:34 UTC |
+-----------------------------------+-----------------------------+----------+----------+----------+--------------+--------+------------------------+------------------------+
| system_distributed                | cdc_streams_descriptions_v2 |     100% |   169KiB |   169KiB |       169KiB |     0B | 23 May 22 12:25:35 UTC | 23 May 22 12:25:35 UTC |
| system_distributed                | view_build_status           |     100% |       0B |       0B |           0B |     0B | 23 May 22 12:25:35 UTC | 23 May 22 12:25:35 UTC |
| system_distributed                | cdc_generation_descriptions |     100% |   169KiB |   169KiB |       169KiB |     0B | 23 May 22 12:25:35 UTC | 23 May 22 12:25:35 UTC |
| system_distributed                | cdc_generation_timestamps   |     100% |     5KiB |     5KiB |         5KiB |     0B | 23 May 22 12:25:35 UTC | 23 May 22 12:25:35 UTC |
+-----------------------------------+-----------------------------+----------+----------+----------+--------------+--------+------------------------+------------------------+
| system_traces                     | node_slow_log_time_idx      |     100% |       0B |       0B |           0B |     0B | 23 May 22 12:25:35 UTC | 23 May 22 12:25:35 UTC |
| system_traces                     | sessions                    |     100% |       0B |       0B |           0B |     0B | 23 May 22 12:25:35 UTC | 23 May 22 12:25:35 UTC |
| system_traces                     | node_slow_log               |     100% |       0B |       0B |           0B |     0B | 23 May 22 12:25:35 UTC | 23 May 22 12:25:35 UTC |
| system_traces                     | sessions_time_idx           |     100% |       0B |       0B |           0B |     0B | 23 May 22 12:25:35 UTC | 23 May 22 12:25:35 UTC |
| system_traces                     | events                      |     100% |       0B |       0B |           0B |     0B | 23 May 22 12:25:35 UTC | 23 May 22 12:25:35 UTC |
+-----------------------------------+-----------------------------+----------+----------+----------+--------------+--------+------------------------+------------------------+
| alternator_bidder-prod-matchtable | bidder-prod-matchtable      |     100% |       0B |       0B |           0B |     0B |                        |                        |
+-----------------------------------+-----------------------------+----------+----------+----------+--------------+--------+------------------------+------------------------+

```

Original discussion: https://scylladb-users.slack.com/archives/CFFVC7EA0/p1653147144460269

### PR DESCRIPTION
**Pull request by Michal-Leszczynski**
Except for fixing reopened (because of dots in table names) issue, this PR also adds a small repair test which validates that alternator tables are also repaired.

Fixes #3165

### CODE REVIEW

File: pkg/service/backup/service_backup_integration_test.go [hunk 1]
```diff
@@ -2315,7 +2311,7 @@ func TestBackupListIntegration(t *testing.T) {
 func TestBackupAlternatorIntegration(t *testing.T) {
 	const (
 		testBucket     = "backuptest-alternator"
-		testTable      = "table-with-dash"
+		testTable      = "table-with.dash-and.dot.-"
```
Comment (karol-kokoszka) [inline pkg/service/backup/service_backup_integration_test.go:2314]: @Michal-Leszczynski can you add the underscore, uppercase chars and digits to the testTable name ? 
It would fulfill this https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.NamingRules then.

Comment (Michal-Leszczynski) [reply pkg/service/backup/service_backup_integration_test.go]: Done, waiting for tests to pass.

**Review by karol-kokoszka — APPROVED** [review]
:+1: please merge
