### PR TITLE
healthcheck: fix deadlock during removal of lost nodes metrics (#2843)

### LINKED ISSUE #2834: Backup task failed 4/4 because of "no space left"
**Issue description**

====================================
There were 48K error messages of "no space left"
```
2021-07-17T01:09:48+00:00  longevity-200gb-48h-verify-limited--db-node-e9b6db72-5 !WARNING | scylla:  [shard 1] commitlog - Exception in segment reservation: storage_io_error (Storage
 I/O error: 28: filesystem error: open failed: No space left on device [/var/lib/scylla/hints/1/10.0.1.244/HintsLog-2-18014398549679702.log])
2021-07-17 01:09:50.000: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=c163a072-9b43-4db3-b22d-68c9d4664815: type=NO_SPACE_ERROR regex=No space left on device line_n
umber=245636 node=Node longevity-200gb-48h-verify-limited--db-node-e9b6db72-5 [13.53.36.212 | 10.0.3.18] (seed: False)
2021-07-17T01:09:50+00:00  longevity-200gb-48h-verify-limited--db-node-e9b6db72-5 !WARNING | scylla:  [shard 13] commitlog - Exception in segment reservation: storage_io_error (Storag
e I/O error: 28: filesystem error: open failed: No space left on device [/var/lib/scylla/hints/13/10.0.1.224/HintsLog-2-234187180663463573.log])
2021-07-17 01:09:52.000: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=c163a072-9b43-4db3-b22d-68c9d4664815: type=NO_SPACE_ERROR regex=No space left on device line_n
umber=245637 node=Node longevity-200gb-48h-verify-limited--db-node-e9b6db72-5 [13.53.36.212 | 10.0.3.18] (seed: False)
2021-07-17T01:09:52+00:00  longevity-200gb-48h-verify-limited--db-node-e9b6db72-5 !WARNING | scylla:  [shard 12] commitlog - Exception in segment reservation: storage_io_error (Storag
e I/O error: 28: filesystem error: open failed: No space left on device [/var/lib/scylla/hints/12/10.0.1.224/HintsLog-2-216172782153981510.log])
```

The backup started at 06:24 on 2021/07/17 and ended at 21:25 on 2021/07/17.
```
< t:2021-07-18 05:09:00,949 f:tester.py       l:181  c:silence              p:DEBUG > Finished 'show_alive_threads'. <class 'OSError'> exception was silenced.
< t:2021-07-18 05:09:00,949 f:base.py         l:140  c:RemoteCmdRunner      p:DEBUG > Command "sudo sctool task list -c adf2861d-6507-453c-9211-6c57ddbb7ecd" finished with status 0
< t:2021-07-18 05:09:00,949 f:cli.py          l:1004 c:sdcm.mgmt.cli        p:DEBUG > sctool output: ╭─────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────���────────────────────────────────────────────────────┬───────────────────────────────┬─────────────╮
< t:2021-07-18 05:09:00,949 f:cli.py          l:1004 c:sdcm.mgmt.cli        p:DEBUG > │ Task                                                        │ Arguments                                                                                                                                                                                                                                                                                                                         │ Next run                      │ Status      │
< t:2021-07-18 05:09:00,949 f:cli.py          l:1004 c:sdcm.mgmt.cli        p:DEBUG > ├─────────────────────────────────────────────────────────────┼──────────────────────���────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────────��─────────────┤
< t:2021-07-18 05:09:00,949 f:cli.py          l:1004 c:sdcm.mgmt.cli        p:DEBUG > │ healthcheck/72526a0d-e04b-4ed6-849f-eeb62ec44166            │                                                                                                                                                                                                                                                                                                                                   │ 18 Jul 21 05:09:10 UTC (+15s) │ DONE        │
< t:2021-07-18 05:09:00,949 f:cli.py          l:1004 c:sdcm.mgmt.cli        p:DEBUG > │ healthcheck_alternator/1920a7a3-9e17-4867-b2df-ed3db7fb917b │                                                                                                                                                                                                                                                                                                                                   │ 18 Jul 21 05:09:10 UTC (+15s) │ DONE        │
< t:2021-07-18 05:09:00,949 f:cli.py          l:1004 c:sdcm.mgmt.cli        p:DEBUG > │ healthcheck_rest/078a1cb7-2236-4df9-a274-5edcc6de5278       │                                                                                                                                                                                                                                                                                                                                   │ 18 Jul 21 05:09:10 UTC (+1m)  │ DONE        │
< t:2021-07-18 05:09:00,949 f:cli.py          l:1004 c:sdcm.mgmt.cli        p:DEBUG > │ backup/5360fbe0-5bf3-480c-a1be-1b76b054b2b3                 │ -K 'drop_table_during_repair_ks_4,drop_table_during_repair_ks_0,drop_table_during_repair_ks_1,drop_table_during_repair_ks_8,drop_table_during_repair_ks_2,drop_table_during_repair_ks_9,keyspace1,drop_table_during_repair_ks_5,drop_table_during_repair_ks_7,drop_table_during_repair_ks_3' -L s3:manager-backup-tests-us-east-1 │                               │ ERROR (4/4) │
< t:2021-07-18 05:09:00,949 f:cli.py          l:1004 c:sdcm.mgmt.cli        p:DEBUG > │ backup/90309286-9a85-4e8d-9f84-8e5a0b616d1a                 │ -L s3:manager-backup-tests-us-east-1                                                                                                                                                                                                                                                                                              │                               │ ERROR (4/4) │
< t:2021-07-18 05:09:00,949 f:cli.py          l:1004 c:sdcm.mgmt.cli        p:DEBUG > │ repair/526f893e-f3c6-45a3-b4ab-24166c5beb11                 │                                                                                                                                                                                                                                                                                                                                   │                               │ DONE        │
< t:2021-07-18 05:09:00,949 f:cli.py          l:1004 c:sdcm.mgmt.cli        p:DEBUG > │ repair/bd62b5d4-7efc-42c7-9ce6-475ab43ed2df                 │                                                                                                                                                                                                                                                                                                                                   │                               │ DONE        │
< t:2021-07-18 05:09:00,949 f:cli.py          l:1004 c:sdcm.mgmt.cli        p:DEBUG > ╰─────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────��───────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────┴─────────────╯
< t:2021-07-18 05:09:00,950 f:cli.py          l:1020 c:sdcm.mgmt.cli        p:DEBUG > sctool res after parsing: [['Task', 'Arguments', 'Next run', 'Status'], ['healthcheck/72526a0d-e04b-4ed6-849f-eeb62ec44166', '', '18 Jul 21 05:09:10 UTC (+15s)', 'DONE'], ['healthcheck_alternator/1920a7a3-9e17-4867-b2df-ed3db7fb917b', '', '18 Jul 21 05:09:10 UTC (+15s)', 'DONE'], ['healthcheck_rest/078a1cb7-2236-4df9-a274-5edcc6de5278', '', '18 Jul 21 05:09:10 UTC (+1m)', 'DONE'], ['backup/5360fbe0-5bf3-480c-a1be-1b76b054b2b3', "-K 'drop_table_during_repair_k:
```

====================================



Restore Monitor Stack command: `$ hydra investigate show-monitor e9b6db72-cd4c-4d02-bc97-7918e841226d`
Show all stored logs command: `$ hydra investigate show-logs e9b6db72-cd4c-4d02-bc97-7918e841226d`

Test id: `e9b6db72-cd4c-4d02-bc97-7918e841226d`


#### Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/e9b6db72-cd4c-4d02-bc97-7918e841226d/20210718_045530/grafana-screenshot-longevity-200gb-48h-scylla-per-server-metrics-nemesis-20210718_045853-longevity-200gb-48h-verify-limited--monitor-node-e9b6db72-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/e9b6db72-cd4c-4d02-bc97-7918e841226d/20210718_045530/grafana-screenshot-longevity-200gb-48h-scylla-per-server-metrics-nemesis-20210718_045853-longevity-200gb-48h-verify-limited--monitor-node-e9b6db72-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/e9b6db72-cd4c-4d02-bc97-7918e841226d/20210718_045530/grafana-screenshot-overview-20210718_045530-longevity-200gb-48h-verify-limited--monitor-node-e9b6db72-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/e9b6db72-cd4c-4d02-bc97-7918e841226d/20210718_045530/grafana-screenshot-overview-20210718_045530-longevity-200gb-48h-verify-limited--monitor-node-e9b6db72-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/e9b6db72-cd4c-4d02-bc97-7918e841226d/20210718_050938/db-cluster-e9b6db72.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9b6db72-cd4c-4d02-bc97-7918e841226d/20210718_050938/db-cluster-e9b6db72.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/e9b6db72-cd4c-4d02-bc97-7918e841226d/20210718_050938/loader-set-e9b6db72.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9b6db72-cd4c-4d02-bc97-7918e841226d/20210718_050938/loader-set-e9b6db72.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/e9b6db72-cd4c-4d02-bc97-7918e841226d/20210718_050938/monitor-set-e9b6db72.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9b6db72-cd4c-4d02-bc97-7918e841226d/20210718_050938/monitor-set-e9b6db72.tar.gz)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/e9b6db72-cd4c-4d02-bc97-7918e841226d/20210718_050938/sct-runner-e9b6db72.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9b6db72-cd4c-4d02-bc97-7918e841226d/20210718_050938/sct-runner-e9b6db72.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/127/)

### LINKED ISSUE #2843: Prometheus endpoint hangs and ends up causing FD starvation
**Scylla Manager version**: 2.4.0-0.20210629.e62d606f
**Issue**: Queries to Scylla Manager metrics endpoint (`curl http://127.0.0.1:56090/metrics`) are hangs forever (i.e: keeps waiting for ~8 minutes and nothing is ever returned). As a side-effect, Scylla Manager may run out of file descriptors when the metrics endpoint is queried frequently.

Restarting the service does not help. For context, this is a large deployment with 12 clusters and ~180 nodes in total.
`lsof` output shows around 20K socket files opened, which seem around too much and may or not be related:

```
grep sock lsof_10783 | wc -l
19892
```

Deployment details (lsof output, `scylla_manager.cluster`, `scylla_manager.repair_run`, `scylla-manager.yaml`, and scylla manager logs) may be found under UUID `04245fd1-4bc6-4e03-9868-05b5aa8a053d`

### PR DESCRIPTION
**Pull request by zimnx**
When buffered channel used for collecting metrics was full,
goroutine trying to write to it was keeping read lock.
Reading side of this channel was deleting metrics which requires taking
a write lock on the same mutex. This resulted in deadlock.

Fixes #2843

### CODE REVIEW

File: pkg/service/healthcheck/metrics.go [hunk 1]
```diff
@@ -145,11 +143,19 @@ func apply(ch <-chan prometheus.Metric, f func(cluster, dc, host, pt string, v f
 	}
 }
 
-func collect(g *prometheus.GaugeVec) chan prometheus.Metric {
-	ch := make(chan prometheus.Metric, metricBufferSize)
+func collect(g *prometheus.GaugeVec) []prometheus.Metric {
+	ch := make(chan prometheus.Metric)
```
Comment (tnozicka) [inline pkg/service/healthcheck/metrics.go:147]: nit: I guess this could still use some buffer for performance

File: pkg/service/healthcheck/metrics.go [hunk 2]
```diff
@@ -145,11 +143,19 @@ func apply(ch <-chan prometheus.Metric, f func(cluster, dc, host, pt string, v f
...
 	go func() {
 		g.Collect(ch)
 		close(ch)
 	}()
-	return ch
+
+	// Collect hold RLock during entire call. Read entire channel to prevent passing channel outside.
```
Comment (tnozicka) [inline pkg/service/healthcheck/metrics.go:153]: nit: holds

Comment (tnozicka) [reply pkg/service/healthcheck/metrics.go:153]: nit: Read the entire channel into an array to prevent passing the channel back where processing particular items could access the same lock and create a deadlock as the Collect function has nowhere to write to until the items are read.

File: pkg/service/healthcheck/metrics_test.go [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+// This test deadlocked when number of metrics exceeded buffered channel length used for collecting metrics.
+// Issue #2843
+func TestRemoveClusterMetricsWhenNumberOfMetricsExceedsDefaultChannelLength_2843(t *testing.T) {
+	clusterID := uuid.MustRandom()
+	metric := prometheus.NewGaugeVec(prometheus.GaugeOpts{
+		Namespace: "scylla_manager",
+		Subsystem: "healthcheck",
+		Name:      "status",
+	}, []string{clusterKey, hostKey})
+	for i := 0; i < 10000; i++ {
```
Comment (tnozicka) [inline pkg/service/healthcheck/metrics_test.go:21]: would it deadlock with just buffersize+1?

**Review by tnozicka — APPROVED** [review]
Good job finding the issue, I agree on the cause.
A few nits, but using the array looks good.

**Comment by tnozicka** [comment]
(feel free to ignore the nits, depending on the urgency)

File: pkg/service/healthcheck/metrics_test.go (hunk 3 above)
Comment (zimnx) [reply pkg/service/healthcheck/metrics_test.go]: not really, because channel needs to be full in order to trigger deadlock. It's also being drained in parallel so there has to be enough items in a queue to fill the channel before it's drained.

Comment (tnozicka) [reply pkg/service/healthcheck/metrics_test.go]: previously there was no buffer so I think apply took only one item then tried calling `f` which got stuck on the lock and didn't proceed to next item - at that point collect could try writing one more value but should get stuck on that because nobody would read it anymore. Think that should hold even with the buffer (just +N)

File: pkg/service/healthcheck/metrics.go [hunk 4]
```diff
@@ -145,11 +145,21 @@ func apply(ch <-chan prometheus.Metric, f func(cluster, dc, host, pt string, v f
...
-func collect(g *prometheus.GaugeVec) chan prometheus.Metric {
+func collect(g *prometheus.GaugeVec) []prometheus.Metric {
 	ch := make(chan prometheus.Metric, metricBufferSize)
 	go func() {
 		g.Collect(ch)
 		close(ch)
 	}()
-	return ch
+
+	// Collect hold RLock during entire call.
```
Comment (tnozicka) [inline pkg/service/healthcheck/metrics.go:155]: nit: holds
