### PR TITLE
Fix timeouts in RepairStatus and LoadSSTables

### LINKED ISSUE #3675: Remove timeouts from synchronous Scylla API calls
Some Scylla endpoints returns only when the operation has been finished. In case this operation is expected to take a long time, we should just hang on the connection and wait for response - not timeout and retry, because it is less efficient and creates confusing error logs. The 2 synchronous calls used with default timeout are:
- StorageServiceRepairStatus: ``` {"L":"INFO","T":"2023-12-01T01:31:54.398Z","N":"cluster.client","M":"HTTP retry backoff","operation":"StorageServiceRepairStatus","wait":"28.607063257s","error":"after 16m0s: context deadline exceeded","_trace_id":"uqSjtDSfRoOl1WhetiLPgA"} ```
- StorageServiceSstablesByKeyspacePost: ``` {"L":"INFO","T":"2023-11-30T23:03:07.117Z","N":"cluster.client","M":"HTTP retry backoff","operation":"StorageServiceSstablesByKeyspacePost","wait":"999.175032ms","error":"after 30s: context deadline exceeded","_trace_id":"uqSjtDSfRoOl1WhetiLPgA"} ```

### PR DESCRIPTION
**Pull request by Michal-Leszczynski**
Both of those calls return from Scylla only when the job is done. Because of that SM shouldn't timeout them on its side (even though it usually works when backoff retry is used).
This PR also includes a small improvement of repair logs mentioned in [here](https://github.com/scylladb/scylla-manager/issues/3671#issuecomment-1870061453).

Fixes #3675

### CODE REVIEW

File: pkg/scyllaclient/client_scylla.go [hunk 1]
```diff
@@ -906,7 +907,7 @@ func (c *Client) LoadSSTables(ctx context.Context, host, keyspace, table string,
 	const WIPError = "Already loading SSTables"
 
 	_, err := c.scyllaOps.StorageServiceSstablesByKeyspacePost(&operations.StorageServiceSstablesByKeyspacePostParams{
-		Context:            forceHost(ctx, host),
+		Context:            noTimeout(forceHost(ctx, host)),
```
Comment (karol-kokoszka) [inline pkg/scyllaclient/client_scylla.go:910]: Please don't use noTimeout.
Use customTimeout instead and set 30m to not hang forever.

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka I added some big timeouts, PTAL.

**Review by karol-kokoszka — APPROVED** [review]
:+1:
