### PR TITLE
Don't add cluster to SM DB before validation finishes

### LINKED ISSUE #4028: Scylla Manager regression in 3.3.2: segmentation fault
Scylla Manager throws segmentation faults in both Scylla Operator CI suites involving Scylla Manager.

https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2089/pull-scylla-operator-master-e2e-gke-parallel/1833059833171939328
https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2089/pull-scylla-operator-master-e2e-gke-parallel/1833059833171939328/artifacts/must-gather/0/namespaces/scylla-manager/pods/scylla-manager-7fb4d59cfc-lpmtz/scylla-manager.previous

```
2024-09-09T09:09:22.233069447Z panic: runtime error: invalid memory address or nil pointer dereference
2024-09-09T09:09:22.233091297Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11da5ac]
```

Artifacts: https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2089/pull-scylla-operator-master-e2e-gke-parallel/1833059833171939328/

---

https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2089/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1833059833192910848
https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2089/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1833059833192910848/artifacts/must-gather/0/namespaces/scylla-manager/pods/scylla-manager-7fb4d59cfc-f5vw8/scylla-manager.previous

```
2024-09-09T09:03:55.901858409Z panic: runtime error: invalid memory address or nil pointer dereference
2024-09-09T09:03:55.901873239Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11da5ac]
```

Artifacts: https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2089/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1833059833192910848/

ScyllaDB Manager version: 3.3.2
ScyllaDB version: tests run with OS 6.1.1 and Enterprise 2024.1.8
ScyllaDB Manager client version: tests run with 3.3.1

With this we can't confirm the supposed fix for https://github.com/scylladb/scylla-manager/issues/3989 is working either.

Xref: https://github.com/scylladb/scylla-operator/pull/2089#issuecomment-2337585017

### PR DESCRIPTION
**Pull request by Michal-Leszczynski**
Commit https://github.com/scylladb/scylla-manager/commit/5bf6b35699c0645ba8598a53516e03ba7e01383f introduced a bug that when adding cluster to SM finished with error,
cluster was still saved in SM DB, but only with the ID and known hosts fields.
That's because method validateHostsConnectivity used discoverAndSetClusterHosts
instead of discoverClusterHosts, which happened before inserting cluster to SM DB.

In case client was mistakenly initialized with "" host, getting host from the pool would panic.
This should be replaced with a simple error. This PR adds additional validation to client config,
which prohibits specifying empty host there. It also makes host pool return an error instead of panic
in case of invalid host pool response.

This PR also includes testes for mentioned issues (validated that those tests weren't passing without the fixes).

Fixes #4028

### CODE REVIEW

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka This PR is ready for review! Failures are connected to #4032.

**Comment by karol-kokoszka** [comment]
Thanks !
I tested it by removing the `host` value in DB directly:
```
➜  scylla-manager git:(ml/fix-4028) cqlsh                                                                                                                                                                                                                       <aws:dbaas-lab-developer>
Connected to SM Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> select * from scylla_manager.cluster;

 id                                   | auth_token | force_non_ssl_session_port | force_tls_disabled | host           | known_hosts                                                                                                  | labels | name | port
--------------------------------------+------------+----------------------------+--------------------+----------------+--------------------------------------------------------------------------------------------------------------+--------+------+------
 f25492d6-be27-41c8-b379-68182411381b |      token |                      False |              False | 192.168.200.11 | {'192.168.200.11', '192.168.200.12', '192.168.200.13', '192.168.200.21', '192.168.200.22', '192.168.200.23'} |   null |      |    0

(1 rows)
cqlsh> update scylla_manager.cluster set host = '';
SyntaxException: line 1:43 : Syntax error
cqlsh> update scylla_manager.cluster set host = '' where id = 
cqlsh> update scylla_manager.cluster set host = '' where id = f25492d6-be27-41c8-b379-68182411381b;
cqlsh> select * from scylla_manager.cluster;

 id                                   | auth_token | force_non_ssl_session_port | force_tls_disabled | host | known_hosts                                                                                                  | labels | name | port
--------------------------------------+------------+----------------------------+--------------------+------+--------------------------------------------------------------------------------------------------------------+--------+------+------
 f25492d6-be27-41c8-b379-68182411381b |      token |                      False |              False |      | {'192.168.200.11', '192.168.200.12', '192.168.200.13', '192.168.200.21', '192.168.200.22', '192.168.200.23'} |   null |      |    0

(1 rows)
cqlsh> exit
➜  scylla-manager git:(ml/fix-4028) cqlsh                                                                                                                                                                                                                       <aws:dbaas-lab-developer>
Connected to SM Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> select * from scylla_manager.cluster;

 id                                   | auth_token | force_non_ssl_session_port | force_tls_disabled | host | known_hosts                                                                                                  | labels | name | port
--------------------------------------+------------+----------------------------+--------------------+------+--------------------------------------------------------------------------------------------------------------+--------+------+------
 f25492d6-be27-41c8-b379-68182411381b |      token |                      False |              False |      | {'192.168.200.11', '192.168.200.12', '192.168.200.13', '192.168.200.21', '192.168.200.22', '192.168.200.23'} |   null |      |    0

(1 rows)
cqlsh> exit
➜  scylla-manager git:(ml/fix-4028) ./sctool.dev cluster update -c f25492d6-be27-41c8-b379-68182411381b --host 192.168.200.13  
```

Scylla-manager started with 
```
13:57:51.145    ERROR   cluster Missing --host flag. Using only previously discovered hosts instead     {"cluster ID": "f25492d6-be27-41c8-b379-68182411381b", "_trace_id": "TqpEHNhfRn-_vRguMF6k8A"}
github.com/scylladb/go-log.Logger.log
        /home/karkok/dev/scylla-manager/vendor/github.com/scylladb/go-log/logger.go:101
github.com/scylladb/go-log.Logger.Error
        /home/karkok/dev/scylla-manager/vendor/github.com/scylladb/go-log/logger.go:84
github.com/scylladb/scylla-manager/v3/pkg/service/cluster.(*Service).discoverClusterHosts
        /home/karkok/dev/scylla-manager/pkg/service/cluster/service.go:179
github.com/scylladb/scylla-manager/v3/pkg/service/cluster.(*Service).discoverAndSetClusterHosts
        /home/karkok/dev/scylla-manager/pkg/service/cluster/service.go:159
github.com/scylladb/scylla-manager/v3/pkg/service/cluster.(*Service).CreateClientNoCache
        /home/karkok/dev/scylla-manager/pkg/service/cluster/service.go:140
github.com/scylladb/scylla-manager/v3/pkg/service/configcache.(*Service).updateSingle
        /home/karkok/dev/scylla-manager/pkg/service/configcache/service.go:157
github.com/scylladb/scylla-manager/v3/pkg/service/configcache.(*Service).updateAll.func1
        /home/karkok/dev/scylla-manager/pkg/service/configcache/service.go:208

```
... what is fine.

Eventually, it is possible to update the host with 
```
➜  scylla-manager git:(ml/fix-4028) ./sctool.dev cluster update -c f25492d6-be27-41c8-b379-68182411381b --host 192.168.200.13                                                                                                                                   <aws:dbaas-lab-developer>
➜  scylla-manager git:(ml/fix-4028) cqlsh                                                                                                                                                                                                                       <aws:dbaas-lab-developer>
Connected to SM Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> select * from scylla_manager.cluster;

 id                                   | auth_token | force_non_ssl_session_port | force_tls_disabled | host           | known_hosts                                                                                                  | labels | name | port
--------------------------------------+------------+----------------------------+--------------------+----------------+--------------------------------------------------------------------------------------------------------------+--------+------+------
 f25492d6-be27-41c8-b379-68182411381b |      token |                      False |              False | 192.168.200.13 | {'192.168.200.11', '192.168.200.12', '192.168.200.13', '192.168.200.21', '192.168.200.22', '192.168.200.23'} |   null |      |    0

(1 rows)

```

**Comment by karol-kokoszka** [comment]
@Michal-Leszczynski can you run operator tests on that ?

File: pkg/service/cluster/service.go [hunk 1]
```diff
@@ -173,10 +173,19 @@ func (s *Service) discoverAndSetClusterHosts(ctx context.Context, c *Cluster) er
 
 func (s *Service) discoverClusterHosts(ctx context.Context, c *Cluster) ([]string, error) {
 	var contactPoints []string
-	contactPoints = append(contactPoints, c.Host)          // Go with the designated contact point first
+	if c.Host != "" {
+		contactPoints = append(contactPoints, c.Host) // Go with the designated contact point first
+	} else {
+		s.logger.Error(ctx, "Missing --host flag. Using only previously discovered hosts instead", "cluster ID", c.ID)
+	}
```
Comment (karol-kokoszka) [inline pkg/service/cluster/service.go:180]: :+1:

**Review by karol-kokoszka — COMMENTED** [review]
PR is OK, let's merge after getting the results from operator tests.

**Comment by Michal-Leszczynski** [comment]
Operator tests started here: https://github.com/scylladb/scylla-operator/pull/2105#issuecomment-2343513126.

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka operator tests passed: https://github.com/scylladb/scylla-operator/pull/2105#issuecomment-2343513126!

**Comment by karol-kokoszka** [comment]
OK, so merging to master and backporting to branch-3.3
let's start the operator tests on the backport PR as well

**Review by karol-kokoszka — APPROVED** [review]
