### PR TITLE
restore: skip mv and si restoration

### LINKED ISSUE #3368: MV and SI should be skip from the restore procedure
Restoration of materialize view and secondary indexes doesn't work with Manager 3.1.
Command fails with information 
```
Error: get resource: create restore units: validate table exists: not found
```
It's because manager checks `system_schema.tables` table against mv and si existence.
Materialize views and secondary indexes are defined in `system_schmea.view` instead.

Manager 3.1 must skip the materialize view and secondary index restoration.
Instead, end user must drop and recreate the materialize view and secondary index after he/she restored all tables.

### PR DESCRIPTION
**Pull request by karol-kokoszka**
Fixes #3368 

---

"Only the Best is Good Enough." - LEGO company motto

Please make sure that:
- Code is split to commits that address a single change
- Commit messages are informative
- Commit titles have module prefix
- Commit titles have issue nr. suffix

### CODE REVIEW

**Comment by Michal-Leszczynski** [comment]
I don't really like the fact that we have to "if-out" MV and SI in different places of the code (creating restore units, iterating over filesMeta). I would say that this type of blacklisting is the responsibility of `RestoreTarget.Keyspace` field, so maybe we should consider blacklisting MV and SI in the same way? This would require us to iterate over all rows in `system_schema.views` in the `GetRestoreTarget`, but that shouldn't be much of a problem.

What do you think about that approach?

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka ^^

**Comment by karol-kokoszka** [comment]
Yes, it make sense to include that into RestoreTarget.
I just made a change in my PR locally, but seems it's not enough to add the view to doNotRestore.

**Comment by Michal-Leszczynski** [comment]
What do you mean by that?
If this is about failing `restoreTablesSmokeIntegration`, then this test should be adjusted, because we skip the `getRestoreTarget` there, but it cannot be skipped in the normal workflow.

**Comment by karol-kokoszka** [comment]
@Michal-Leszczynski You are right !
It was enough to update GetRestoreTarget.
Test is updated.

File: pkg/service/backup/restore.go [hunk 1]
```diff
@@ -64,6 +66,14 @@ func (s *Service) GetRestoreTarget(ctx context.Context, clusterID uuid.UUID, pro
...
 			t.Keyspace = append(t.Keyspace, "!"+ks)
 		}
+
+		views, err := s.listAllViews(ctx, clusterID)
+		if err != nil {
+			return t, errors.Wrapf(err, "list all views of cluster %s", clusterID.String())
+		}
+		for _, viewName := range views {
+			t.Keyspace = append(t.Keyspace, "!"+viewName)
+		}
```
Comment (Michal-Leszczynski) [inline pkg/service/backup/restore.go:76]: Maybe add a comment here why do not support restoration of MV and SI.

File: pkg/service/backup/restore.go [hunk 2]
```diff
@@ -244,3 +254,29 @@ func (s *Service) forEachRestoredManifest(clusterID uuid.UUID, target RestoreTar
 		return s.forEachManifest(ctx, clusterID, []Location{location}, filter, f)
 	}
 }
+
+// listAllViews is the utility function that queries system_schema.views table to get list of all views created on the cluster.
+func (s *Service) listAllViews(ctx context.Context, clusterID uuid.UUID) (views []string, err error) {
```
Comment (Michal-Leszczynski) [inline pkg/service/backup/restore.go:259]: Maybe it's worth to mention that the `system_schema.views` also contains indexes?
It wasn't clear for me why we only query this table and not the `system_schema.indexes`.

File: pkg/service/backup/restore.go [hunk 3]
```diff
@@ -244,3 +254,29 @@ func (s *Service) forEachRestoredManifest(clusterID uuid.UUID, target RestoreTar
...
+			err = multierr.Append(err, err2)
+		}
+	}()
+
+	var keyspace, view string
+	for iter.Scan(&keyspace, &view) {
+		views = append(views, keyspace+"."+view)
+	}
+
+	return
```
Comment (Michal-Leszczynski) [inline pkg/service/backup/restore.go:281]: What is the need for this defer and error appending?
If we get to the point of defer, err always equals nil.
Wouldn't it be nicer to get rid of named return and write:
```go
	var keyspace, view string
	for iter.Scan(&keyspace, &view) {
		views = append(views, keyspace+"."+view)
	}

	return iter.Close()
```

File: pkg/service/backup/service_backup_restore_integration_test.go [hunk 4]
```diff
@@ -335,21 +335,40 @@ func TestRestoreTablesSmokeIntegration(t *testing.T) {
...
+{
+  "location": %s,
+  "keyspace": [
+    "%s"
+  ],
+  "snapshot_tag": "sm_20060102150405UTC",
+  "batch_size": %d,
+  "parallel": %d,
+  "restore_tables": true
+}`, locStr, testKeyspace, testBatchSize, testParallel)
```
Comment (Michal-Leszczynski) [inline pkg/service/backup/service_backup_restore_integration_test.go:359]: I really like the idea to store restore parameters as json, so that we can properly use `GetRestoreTarget` in the tests!

But it could be the case for more tests than just the `testRestoreTablesSmokeIntegration`! Moreover, it does not feel good that we have to hardcode some random snapshot_tag just for the `GetRestoreTarget` to pass and than swap it with an actual one. 
For those reasons, maybe we could write a function, which could take restore task params and convert them to a json accepted by the `GetRestoreTarget`. Maybe this function could accept `RestoreTarget` for simplicity? Then, this function should be used in all restore tests which would also make them more robust.

File: pkg/service/backup/service_backup_restore_integration_test.go [hunk 5]
```diff
@@ -362,40 +381,55 @@ func TestRestoreSchemaSmokeIntegration(t *testing.T) {
...
 		srcClientCfg = scyllaclient.TestConfig(ManagedSecondClusterHosts(), AgentAuthToken())
 		mgrSession   = CreateScyllaManagerDBSession(t)
-		dstSession   = CreateSessionAndDropAllKeyspaces(t, ManagedClusterHosts())
-		srcSession   = CreateSessionAndDropAllKeyspaces(t, ManagedSecondClusterHosts())
-		dstH         = newRestoreTestHelper(t, mgrSession, cfg, target.Location[0], nil)
-		srcH         = newRestoreTestHelper(t, mgrSession, cfg, target.Location[0], &srcClientCfg)
+		dstH         = newRestoreTestHelper(t, mgrSession, cfg, location, nil)
+		srcH         = newRestoreTestHelper(t, mgrSession, cfg, location, &srcClientCfg)
+		dstSession   gocqlx.Session
+		srcSession   gocqlx.Session
```
Comment (Michal-Leszczynski) [inline pkg/service/backup/service_backup_restore_integration_test.go:416]: Maybe it's worth to leave the basic `restoreTablesSmokeIntegration` test and write a brand new one for this case? This would perhaps allow us to avoid the ifology in `smokeRestore` function in favor of creating another one.

**Review by Michal-Leszczynski — CHANGES_REQUESTED** [review]

File: pkg/service/backup/restore.go (hunk 2 above)
Comment (karol-kokoszka) [reply pkg/service/backup/restore.go:259]: Index actually is a view that shows the table ordered according to the index definition.
But I can add comment about that anyway.

File: pkg/service/backup/service_backup_restore_integration_test.go (hunk 4 above)
Comment (karol-kokoszka) [reply pkg/service/backup/service_backup_restore_integration_test.go:359]: Sure, I can remove snapshot_tag from the payload definition.
But I'm not gonna refactor other tests now.

Please propose follow up PR if you see it as something really helpfull and needed.

File: pkg/service/backup/service_backup_restore_integration_test.go (hunk 5 above)
Comment (karol-kokoszka) [reply pkg/service/backup/service_backup_restore_integration_test.go:416]: I don't think it make sense to leave previous restoreTablesSmokeIntegration.
It did almost the same what the current one does.
The difference is that the current one restores the schema the "universal restore" way + current one creates materialized view + secondary index in backup.

File: pkg/service/backup/service_backup_restore_integration_test.go (hunk 4 above)
Comment (karol-kokoszka) [reply pkg/service/backup/service_backup_restore_integration_test.go:359]: UPDATE: I cannot remove snapshot_tag.
This field cannot be empty https://github.com/scylladb/scylla-manager/blob/803d2919ccbca134cfe9fc3437cd88a642abd9a1/pkg/service/backup/restore_model.go#L23

Test fails with "not a Scylla Manager snapshot tag, expected format is sm_20060102150405UTC" on GetRestoreTarget() call if the field is empty.
