### PR TITLE
fix(healtcheck): make native cql to retry if connection is failed

### LINKED ISSUE #3550: cqlping.NativeCQLPing should have retry

### PR DESCRIPTION
**Pull request by dkropachev**
Fixes #3550 

Customers complain that healthcheck fails on cqlping having almost no load on the cluster and network working perfectly fine.

### CODE REVIEW

**Comment by karol-kokoszka** [comment]
Native CQL ping is executed when scylla-manager doesn't hold CQL credentials to the cluster.
The customer who complains is the cloud one or the enterprise one ? 
All cloud clusters have credentials available already.

I'm not sure if the retry solves the problem. It couldn't connect and it's reported as FAIL what is correct.

**Comment by dkropachev** [comment]
> Native CQL ping is executed when scylla-manager doesn't hold CQL credentials to the cluster. The customer who complains is the cloud one or the enterprise one ? All cloud clusters have credentials available already.
> 
> I'm not sure if the retry solves the problem. It couldn't connect and it's reported as FAIL what is correct.

Customer pointed to exactly that case, they mentioned that hey don't have credentials.
But despite that, failure of singular tcp connection request should not trigger healthcheck failure.

**Comment by karol-kokoszka** [comment]
This code snippet shows that manager is logging the exact error on CQL ping failure.
Customer can check if it's the `timeout` error or something else https://github.com/scylladb/scylla-manager/blob/e51531ddb257bf19f217a60cd4922ff6975b8b8f/pkg/ping/error.go#L9

https://github.com/scylladb/scylla-manager/blob/e51531ddb257bf19f217a60cd4922ff6975b8b8f/pkg/service/healthcheck/service.go#L219-L226

The solution you want to apply makes sense only if the root cause is not the timeout on establishing connection, but something else, like immediate rejection.

Have a look here https://github.com/scylladb/scylla-manager/blob/e51531ddb257bf19f217a60cd4922ff6975b8b8f/pkg/ping/cqlping/cqlping.go#L49-L63

^^ dialer keeps exactly the same timeout as what is passed to the backoff = `config.Timeout`
`	backoff := retry.NewExponentialBackoff(time.Millisecond, config.Timeout, config.Timeout/3, 2, 0)`

If the root cause is some immediate rejection, then we will have it in logs.

**Comment by karol-kokoszka** [comment]
Although, I'm fine with the PR, just fix the sanity-checks that are failing.

**Comment by dkropachev** [comment]
> This code snippet shows that manager is logging the exact error on CQL ping failure. Customer can check if it's the `timeout` error or something else
> 
> https://github.com/scylladb/scylla-manager/blob/e51531ddb257bf19f217a60cd4922ff6975b8b8f/pkg/ping/error.go#L9
> 
> https://github.com/scylladb/scylla-manager/blob/e51531ddb257bf19f217a60cd4922ff6975b8b8f/pkg/service/healthcheck/service.go#L219-L226
> 
> The solution you want to apply makes sense only if the root cause is not the timeout on establishing connection, but something else, like immediate rejection.
> 
> Have a look here
> 
> https://github.com/scylladb/scylla-manager/blob/e51531ddb257bf19f217a60cd4922ff6975b8b8f/pkg/ping/cqlping/cqlping.go#L49-L63
> 
> ^^ dialer keeps exactly the same timeout as what is passed to the backoff = `config.Timeout` ` backoff := retry.NewExponentialBackoff(time.Millisecond, config.Timeout, config.Timeout/3, 2, 0)`
> 
> If the root cause is some immediate rejection, then we will have it in logs.

Sure, I have already asked to provide additional information on the issue.

**Comment by dkropachev** [comment]
@karol-kokoszka , all linter complaints addressed, test is fixed, fail you see on backup is not related to the PR.

File: pkg/ping/cqlping/cqlping.go [hunk 1]
```diff
@@ -33,21 +34,30 @@ var options = []byte{4, 0, 0, 0, 5, 0, 0, 0, 0}
...
 // It returns rtt and error.
 func NativeCQLPing(ctx context.Context, config Config) (rtt time.Duration, err error) {
+	backoff := retry.NewExponentialBackoff(time.Millisecond, config.Timeout, config.Timeout/3, 2, 0)
+	deadline := timeutc.Now().Add(config.Timeout)
 	t := timeutc.Now()
-	defer func() {
-		rtt = timeutc.Since(t)
-		if rtt >= config.Timeout {
-			err = ping.ErrTimeout
+	for attempt := 0; ; attempt++ {
```
Comment (karol-kokoszka) [inline pkg/ping/cqlping/cqlping.go:40]: what is this variable for ? 
I see no checks made on `attempt`.
It can be replaced with for {}

File: pkg/ping/cqlping/cqlping.go [hunk 2]
```diff
@@ -33,21 +34,30 @@ var options = []byte{4, 0, 0, 0, 5, 0, 0, 0, 0}
...
+		err = nativeCQLPingOnce(ctx, config, deadline)
+		if err == nil {
+			return timeutc.Since(t), nil
 		}
-	}()
+		duration := backoff.NextBackOff()
+		if duration == retry.Stop {
+			return timeutc.Since(t), ping.ErrTimeout
+		}
+		time.Sleep(duration)
```
Comment (karol-kokoszka) [inline pkg/ping/cqlping/cqlping.go:49]: Please log the information about retries (attempt variable may be useful then).

Comment (dkropachev) [reply pkg/ping/cqlping/cqlping.go:52]: done

File: pkg/ping/cqlping/cqlping.go (hunk 1 above)
Comment (dkropachev) [reply pkg/ping/cqlping/cqlping.go]: it is reused for the logging

**Review by karol-kokoszka — APPROVED** [review]

**Comment by mykaul** [comment]
I'm hoping this doesn't hide issues...
