### PR TITLE
fix(repair): update params of disabled tasks using its names only

### LINKED ISSUE #3513: Make sure it's possible to re-enable disabled task using task name instead of just the task ID
I previously used the command "sctool stop -c my-cluster-name --disable repair/all-weekly" to temporarily disable repairs while doing some work on my cluster, and now I want to enable it, but can't find anything in the docs on how to do this.

The "sctool start" command doesn't seem to have an option for this. "sctool tasks resume" also doesn't seem to do the trick.

I tried to modify an example like this "sctool repair update -c my-cluster-name repair/all-weekly --enabled=true", but that returned "Error: no tasks of type repair". But if I do "sctool tasks -a", I do see the repair/all-weekly task in the list with an asterisk in front of it.

Let me know the trick, thanks.

### PR DESCRIPTION
**Pull request by karol-kokoszka**
Fixes #3513 

---

"Only the Best is Good Enough." - LEGO company motto

Please make sure that:
- Code is split to commits that address a single change
- Commit messages are informative
- Commit titles have module prefix
- Commit titles have issue nr. suffix

### CODE REVIEW

File: pkg/managerclient/client.go [hunk 1]
```diff
@@ -406,11 +406,13 @@ func (c *Client) uniqueTaskID(ctx context.Context, clusterID, taskType string) (
 }
 
 func (c *Client) taskByName(ctx context.Context, clusterID, taskType, taskName string) (uuid.UUID, error) {
+	all := true
 	resp, err := c.operations.GetClusterClusterIDTasks(&operations.GetClusterClusterIDTasksParams{
 		Context:   ctx,
 		ClusterID: clusterID,
 		Type:      &taskType,
 		Short:     pointer.BoolPtr(true),
+		All:       &all,
```
Comment (Michal-Leszczynski) [inline pkg/managerclient/client.go:415]: Why not use `pointer.BoolPtr(true)` like above?

Comment (karol-kokoszka) [reply pkg/managerclient/client.go:415]: shame on me :) fixing...

**Review by Michal-Leszczynski — APPROVED** [review]
My only concern would be about handling deleted/disabled tasks in the other parts of code. I believe that this change makes it possible to run into #3514 when using task name, but this can still happen now when using task ID and it's a bug in different parts of code.
