### PR TITLE
fix(scyllaclient): report correct password protection status with full authenticator name

### LINKED ISSUE #3495: Restoring a snapshot into a cluster with authentication enabled fails: `unable to create session: unable to discover protocol version: authentication required`
## Issue description

First, we added the cluster to the manager
```
< t:2023-07-20 10:21:37,239 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "sudo sctool cluster add --host=10.4.3.18  --name=longevity-200gb-48h-verify-limited--db-cluster-f296d884 --auth-token f296d884-316b-41b4-9406-a9090ec196ea --username cassandra --password cassandra" finished with status 0
< t:2023-07-20 10:21:37,244 f:cli.py          l:1114 c:sdcm.mgmt.cli        p:DEBUG > sctool output: ae818ceb-b9c2-405e-9d37-5021b423f487
```
Afterwards, we tried to restore a (previously created) snapshot, and the restore command failed due to missing authentication:
```
< t:2023-07-20 10:21:43,898 f:nemesis.py      l:4591 c:sdcm.nemesis         p:ERROR > Command: 'sudo sctool restore -c ae818ceb-b9c2-405e-9d37-5021b423f487 --restore-schema --location s3:manager-backup-tests-permanent-snapshots-us-east-1  --snapshot-tag sm_20230702173940UTC'
< t:2023-07-20 10:21:43,898 f:nemesis.py      l:4591 c:sdcm.nemesis         p:ERROR > 
< t:2023-07-20 10:21:43,898 f:nemesis.py      l:4591 c:sdcm.nemesis         p:ERROR > Exit code: 1
< t:2023-07-20 10:21:43,898 f:nemesis.py      l:4591 c:sdcm.nemesis         p:ERROR > 
< t:2023-07-20 10:21:43,898 f:nemesis.py      l:4591 c:sdcm.nemesis         p:ERROR > Stdout:
< t:2023-07-20 10:21:43,898 f:nemesis.py      l:4591 c:sdcm.nemesis         p:ERROR > 
< t:2023-07-20 10:21:43,898 f:nemesis.py      l:4591 c:sdcm.nemesis         p:ERROR > 
< t:2023-07-20 10:21:43,898 f:nemesis.py      l:4591 c:sdcm.nemesis         p:ERROR > 
< t:2023-07-20 10:21:43,898 f:nemesis.py      l:4591 c:sdcm.nemesis         p:ERROR > Stderr:
< t:2023-07-20 10:21:43,898 f:nemesis.py      l:4591 c:sdcm.nemesis         p:ERROR > 
< t:2023-07-20 10:21:43,898 f:nemesis.py      l:4591 c:sdcm.nemesis         p:ERROR > Error: create restore units: get CQL cluster session: gocql: unable to create session: unable to discover protocol version: authentication required (using "org.apache.cassandra.auth.PasswordAuthenticator")
< t:2023-07-20 10:21:43,898 f:nemesis.py      l:4591 c:sdcm.nemesis         p:ERROR > Trace ID: lZwtNmQ3QXqCUj1RrEgaEQ (grep in scylla-manager logs)
```
Grepped rows from the log:
```
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:40 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:40.186Z","N":"backup","M":"GetRestoreTarget","cluster_id":"ae818ceb-b9c2-405e-9d37-5021b423f487","_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:40 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:40.186Z","N":"backup","M":"No datacenter specified for location - using all nodes for this location","location":"s3:manager-backup-tests-permanent-snapshots-us-east-1","_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:40 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:40.186Z","N":"cluster","M":"Creating new Scylla REST client","cluster_id":"ae818ceb-b9c2-405e-9d37-5021b423f487","_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:40 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:40.205Z","N":"cluster.client","M":"Measuring datacenter latencies","dcs":["eu-west"],"_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:40 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:40.234Z","N":"cluster.client","M":"Checking hosts connectivity","hosts":["10.4.1.140","10.4.3.18","10.4.3.190","10.4.3.39"],"_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:40 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:40.236Z","N":"cluster.client","M":"Host check OK","host":"10.4.3.39","_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:40 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:40.236Z","N":"cluster.client","M":"Host check OK","host":"10.4.3.18","_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:40 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:40.237Z","N":"cluster.client","M":"Host check OK","host":"10.4.3.190","_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:40 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:40.243Z","N":"cluster.client","M":"Host check OK","host":"10.4.1.140","_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:40 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:40.243Z","N":"cluster.client","M":"Done checking hosts connectivity","_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:41 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:41.903Z","N":"cluster.client","M":"Host location access check OK","host":"10.4.3.190","location":"s3:manager-backup-tests-permanent-snapshots-us-east-1","_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:41 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:41.930Z","N":"cluster.client","M":"Host location access check OK","host":"10.4.3.18","location":"s3:manager-backup-tests-permanent-snapshots-us-east-1","_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:41 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:41.934Z","N":"cluster.client","M":"Host location access check OK","host":"10.4.3.39","location":"s3:manager-backup-tests-permanent-snapshots-us-east-1","_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:42 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:42.039Z","N":"cluster.client","M":"Host location access check OK","host":"10.4.1.140","location":"s3:manager-backup-tests-permanent-snapshots-us-east-1","_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:42 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:42.039Z","N":"cluster","M":"Creating new Scylla REST client","cluster_id":"ae818ceb-b9c2-405e-9d37-5021b423f487","_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:42 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:42.054Z","N":"cluster.client","M":"Measuring datacenter latencies","dcs":["eu-west"],"_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
monitor-set-f296d884/longevity-200gb-48h-verify-limited--monitor-node-f296d884-1/scylla_manager.log:Jul 20 10:21:42 longevity-200gb-48h-verify-limited--monitor-node-f296d884-1 scylla-manager[30171]: {"L":"INFO","T":"2023-07-20T10:21:42.125Z","N":"http","M":"POST /api/v1/cluster/ae818ceb-b9c2-405e-9d37-5021b423f487/tasks","from":"127.0.0.1:54542","status":500,"bytes":251,"duration":"1941ms","error":"create restore units: get CQL cluster session: gocql: unable to create session: unable to discover protocol version: authentication required (using \"org.apache.cassandra.auth.PasswordAuthenticator\")","_trace_id":"lZwtNmQ3QXqCUj1RrEgaEQ"}
```

## Impact

Users that have authentication enabled on their clusters could potentially be unable to use the restore ability.

## How frequently does it reproduce?

Reproduce constantly over the last several runs.

## Installation details

Kernel Version: 5.15.0-1039-aws
Scylla version (or git commit hash): `2022.2.11-20230705.27d29485de90` with build-id `f467a0ad8869d61384d8bbc8f20e4fb8fd281f4b`
Client version: 3.1.2-0.20230704.bd349aa4
Server version: 3.1.2-0.20230704.bd349aa4

Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-200gb-48h-verify-limited--db-node-f296d884-4 (52.211.25.27 | 10.4.3.39) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-f296d884-3 (3.253.44.241 | 10.4.3.190) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-f296d884-2 (54.170.182.100 | 10.4.1.140) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-f296d884-1 (176.34.152.129 | 10.4.3.18) (shards: 14)

OS / Image: `ami-0e981bde054209883` (aws: eu-west-1)

Test: `longevity-200gb-48h-test_restore-nemesis`
Test id: `f296d884-316b-41b4-9406-a9090ec196ea`
Test name: `scylla-staging/Shlomo/longevity-200gb-48h-test_restore-nemesis`
Test config file(s):

- [longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2e89a9eb38a4affbf664835d861415aa2bccad6e/test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor f296d884-316b-41b4-9406-a9090ec196ea`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f296d884-316b-41b4-9406-a9090ec196ea)
- Show all stored logs command: `$ hydra investigate show-logs f296d884-316b-41b4-9406-a9090ec196ea`

## Logs:
- **db-cluster-f296d884.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f296d884-316b-41b4-9406-a9090ec196ea/20230720_115224/db-cluster-f296d884.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f296d884-316b-41b4-9406-a9090ec196ea/20230720_115224/db-cluster-f296d884.tar.gz)
- **sct-runner-events-f296d884.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f296d884-316b-41b4-9406-a9090ec196ea/20230720_115224/sct-runner-events-f296d884.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f296d884-316b-41b4-9406-a9090ec196ea/20230720_115224/sct-runner-events-f296d884.tar.gz)
- **sct-f296d884.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f296d884-316b-41b4-9406-a9090ec196ea/20230720_115224/sct-f296d884.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f296d884-316b-41b4-9406-a9090ec196ea/20230720_115224/sct-f296d884.log.tar.gz)
- **loader-set-f296d884.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f296d884-316b-41b4-9406-a9090ec196ea/20230720_115224/loader-set-f296d884.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f296d884-316b-41b4-9406-a9090ec196ea/20230720_115224/loader-set-f296d884.tar.gz)
- **monitor-set-f296d884.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f296d884-316b-41b4-9406-a9090ec196ea/20230720_115224/monitor-set-f296d884.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f296d884-316b-41b4-9406-a9090ec196ea/20230720_115224/monitor-set-f296d884.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/Shlomo/job/longevity-200gb-48h-test_restore-nemesis/11/)
[Argus](https://argus.scylladb.com/test/226c0f08-de6f-4d69-8f77-b01161019748/runs?additionalRuns[]=f296d884-316b-41b4-9406-a9090ec196ea)
</details>

### PR DESCRIPTION
**Pull request by dkropachev**
Closes #3495

### CODE REVIEW

File: pkg/scyllaclient/config_client.go [hunk 1]
```diff
@@ -158,7 +158,7 @@ func (c *ConfigClient) CQLPasswordProtectionEnabled(ctx context.Context) (bool,
 	if err != nil {
 		return false, err
 	}
-	return resp.Payload == passwordAuthenticator, err
+	return strings.Replace(resp.Payload, "org.apache.cassandra.auth", "", 1) == passwordAuthenticator, err
```
Comment (karol-kokoszka) [inline pkg/scyllaclient/config_client.go:161]: `org.apache.cassandra.auth.PasswordAuthenticator` is the string
you forgot the last dot `.`

should be 
```
return strings.Replace(resp.Payload, "org.apache.cassandra.auth.", "", 1) == passwordAuthenticator, err
```

**Review by karol-kokoszka — APPROVED** [review]

File: pkg/scyllaclient/config_client.go (hunk 1 above)
Comment (dkropachev) [reply pkg/scyllaclient/config_client.go]: updated, thanks
